# Generated by Django 2.1.3 on 2021-04-18 19:18

import bboard.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0003_auto_20210418_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bb',
            name='content',
            field=models.TextField(blank=True, null=True, validators=[bboard.validators.min_5_chars], verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='title',
            field=models.CharField(error_messages={'invalid': 'Неправильное название товара'}, max_length=50, validators=[bboard.validators.min_5_chars], verbose_name='Товар'),
        ),
    ]
